### ISSUE TITLE
 Can you provide the code for video data preprocessing?

### ISSUE THREAD

**Issue by longmalongma** [boheumd/MA-LMM#17]
We are currently following your masterpiece MA-LLM, but we are encountering issues with video data preprocessing. It seems that you do not have publicly available code for video data preprocessing. Can you provide the code for video data preprocessing? If possible, thank you very much.

**Comment by boheumd** [comment]
Hello, for the video data processing, you can refer to this issue https://github.com/boheumd/MA-LMM/issues/3 for more help. Currently, we extract frames from videos with 10 fps.

**Comment by boheumd** [comment]
Hi, I updated the README.md. The example preprocessing code is provided here https://github.com/boheumd/MA-LMM/blob/main/data/extract_frames.py
