### ISSUE TITLE
Curious about the experimental stability？

### ISSUE THREAD

**Issue by vhzy** [boheumd/MA-LMM#18]
I modified the model and evaluation codes to train and test on the NEXT-QA dataset. However, there is about a 1% point fluctuation in the results during each training run. Are the experimental results stable during the training process? I suspect this variability might stem from certain parameter settings of the large language model (LLM). Do you have any empirical suggestions to address this issue? Thank you!

**Comment by boheumd** [comment]
Hello, for the 1% point fluctuation of the results, are those for the testing dataset or training dataset?

**Comment by vhzy** [comment]
Sorry, I re-ran your code and the result is stable. There were some bugs
before. Thanks for your reply!



Bo He ***@***.***> 于2024年5月29日周三 22:30写道：
