### ISSUE TITLE
dataset processing

### ISSUE THREAD

**Issue by haoranD** [boheumd/MA-LMM#2]
Hi,

Thanks for your amazing work.

I can only find the download script for msrvtt and msvd in lavis folder.

Could you share more details about downloading, organizing and preprocessing for other datasets?

Thanks a lot.

Best

**Comment by boheumd** [comment]
Hello! Currently, the downloading script only supports the MSRVTT and MSVD datasets. To obtain other datasets, please refer to the provided links and download the videos using the official download links associated with each dataset. Afterward, you can preprocess the videos by extracting frames at a frequency of 10 frames per second (fps=10) to prepare the dataset for use. Please note that the downloading script does not yet support other datasets, but I plan to add support for more datasets in the future.
