### ISSUE TITLE
Will reducing the batch size for training from 32 to 4 result in performance loss?

### ISSUE THREAD

**Issue by longmalongma** [boheumd/MA-LMM#20]
hi, We are replicating your work, using 4-card 4090. During training, we need to reduce the batch size from 32 to 4. Will this result in a significant loss of performance?

**Comment by boheumd** [comment]
Hi, in this case, you can increase the run.accum_grad_iters from 1 to 8 to keep the total batch size 32 unchanged.

**Comment by longmalongma** [comment]
> Hi, in this case, you can increase the run.accum_grad_iters from 1 to 8 to keep the total batch size 32 unchanged.

Thank you for your reply. This can prevent performance loss, right?

**Comment by boheumd** [comment]
> > Hi, in this case, you can increase the run.accum_grad_iters from 1 to 8 to keep the total batch size 32 unchanged.
> 
> Thank you for your reply. This can prevent performance loss, right?

I did not try this before, but I think it can prevent the performance loss.

**Comment by longmalongma** [comment]
> > > Hi, in this case, you can increase the run.accum_grad_iters from 1 to 8 to keep the total batch size 32 unchanged.
> > 
> > 
> > Thank you for your reply. This can prevent performance loss, right?
> 
> I did not try this before, but I think it can prevent the performance loss.

Ok. Thank you very much!
