### ISSUE TITLE
LVU, COIN dataset

### ISSUE THREAD

**Issue by nisargshah1999** [boheumd/MA-LMM#21]
Hi, Thanks for interesting work
Would it be possible to share the LVU and COIN dataset; 
Also, any codes to preprocess them as I couldn't find any information on lavis/datasets/download_videoes

Thanks

**Comment by boheumd** [comment]
Hi, you can download LVU and COIN dataset through the link provided in the README file.
For the data preprocess, simply extracting video frames at an fps=10 is enough.

**Comment by boheumd** [comment]
Hi, I updated the README.md. The example preprocessing code is provided here https://github.com/boheumd/MA-LMM/blob/main/data/extract_frames.py
