### ISSUE TITLE
Question about the query memory bank

### ISSUE THREAD

**Issue by LiJiaqi96** [boheumd/MA-LMM#22]
![figure2](https://github.com/boheumd/MA-LMM/assets/39684910/2fca8f9e-f223-41fa-9c2f-5e965f76d6db)
Hi, thanks for your excellent work for long video understanding! I have some questions about the query memory bank:  
- What is the intuition of using the cascade Q-Former with l layers (rather than T)?  
- It seems that with the increase of time, the size of memory bank also increases until reaching the maximum limit. So does the model using different Q-Former for each time step t?  
- I could not understand the evolve of z_t. I suppose the query memory bank stores the [z_1, z_2, ..., z_t] but the figure 2 in the paper shows that there are several query memory banks. Could you please help me clarify this point?  
  
Many thanks!

**Comment by boheumd** [comment]
Hi, thank you for your interest.
1. We follow the standard Q-Former architecture used in BLIP2/InstructBLIP, which consists of 12 Q-Former blocks.
2. Our model uses the same Q-Former. But during the online processing of video frames, the memory bank size will increase until reaching the maximum limit. 
3. Each Q-Former block has its own query memory banks. So there are 12 query memory banks.

**Comment by LiJiaqi96** [comment]
Thanks for your reply! I misunderstand the structure of your Q-Former. It is clear that the illustration is different blocks of Q-Former.

**Comment by Edwardmark** [comment]
@boheumd Hi, thanks for your great work. I have some question about the llm generation phase.
1. When the model do generation? Does it generation words for each frame when accepting the last frame query vector?
2. What is the actual input when decoding? Does the input includes the caption already generated and the prompt and the query vector z_t? Any other inputs? 
3. What is saved as kv cache? 

Thanks.
