### ISSUE TITLE
Run demo.ipynb

### ISSUE THREAD

**Issue by seTalent** [boheumd/MA-LMM#28]
Hello. I opened the demo file and got this result, what is wrong with it? 

The vicuna is lmsys/vicuna-7b-v1.5.

Thanks!

**Comment by seTalent** [comment]
![image](https://github.com/user-attachments/assets/9a632862-facc-46c3-bcbc-f231626923cb)

**Comment by boheumd** [comment]
Hi, you should download vicuna-v1.1 instead of v1.5 according to the README file.
