### ISSUE TITLE
Query memory bank

### ISSUE THREAD

**Issue by hulianyuyy** [boheumd/MA-LMM#29]
I can find the visual memory bank in blip2_vicuna_instruct.py, but i can't find the query memory bank described in the paper. May i request your help?

**Comment by lxrrrrrr** [comment]
In my understanding, query memory bank refers to a virtual concept that refers to the image_imbeds information encoded by clip

**Comment by hulianyuyy** [comment]
I don't think so. As pointed in the paper, the query memory bank is the accumulated query tensors along the temporal dimension. Besides, the image_imbeds tensors are used to construct the visual memory bank.

**Comment by lxrrrrrr** [comment]
Sorry it was my mistake, the virtual concept I was referring to was the Visual Memory Bank in the paper, and the visual_memory_bank in the code was the Query Memory Bank in the paper

**Comment by hulianyuyy** [comment]
It can be found that the visual_memory_bank in the code is constructed by the image_imbeds, which refers to the visual memory bank in the paper. However, the query memory bank which is constructed by the query tensors are not found in the code.

**Comment by boheumd** [comment]
Hi, the query_memory_bank can be found here https://github.com/boheumd/MA-LMM/blob/main/lavis/models/blip2_models/blip2.py#L166

**Comment by hulianyuyy** [comment]
Many thanks for your reply!
