### ISSUE TITLE
How to train this code on my own dataset to achieve the task of video captioning???

### ISSUE THREAD

**Issue by Zeyu1226-mt** [boheumd/MA-LMM#33]
It is a very meaningful work. I want to know how can i train on my own dataset to achieve the task of video captioning???

**Comment by M117n** [comment]
To fine tune the model downloading the weights from [https://github.com/salesforce/LAVIS/tree/main/projects/instructblip](InstructBlip) and then run the following commando:

`bash run_scripts/${dataset}/train.sh`

Of course, substituting 'dataset' with the directory of the train  data you want to use. The also provide finetuning checkpoints #32.

**Comment by Zeyu1226-mt** [comment]
> To fine tune the model downloading the weights from [https://github.com/salesforce/LAVIS/tree/main/projects/instructblip](InstructBlip) and then run the following commando:
> 
> `bash run_scripts/${dataset}/train.sh`
> 
> Of course, substituting 'dataset' with the directory of the train data you want to use. The also provide finetuning checkpoints #32.

Ok,i will try it....Thank you very much. Your work is very meaningful.
