### ISSUE TITLE
zero shot demo

### ISSUE THREAD

**Issue by lien99** [boheumd/MA-LMM#6]
I want to simply run the project demo, just like the jupyter example of blip in the lavis library. How can I do it?

**Comment by mvsoom** [comment]
Me too :)

**Comment by boheumd** [comment]
Hi, we are working on this and plan to release it soon.

**Comment by zdaiot** [comment]
@boheumd hello，any progress, please?

**Comment by boheumd** [comment]
@xjtulien @mvsoom @zdaiot Hello, the demo is now released in the latest version. Thank you for your patience.

**Comment by mvsoom** [comment]
Hi @boheumd, thank you so much for the quick release of the demo. It works perfectly on a A10.
