### ISSUE TITLE
hugging face access token problem

### ISSUE THREAD

**Issue by minjung98** [boheumd/MA-LMM#7]
When I run the following section in 'demo.ipynb':

`model, vis_processors, _ = load_model_and_preprocess(
    name="blip2_vicuna_instruct_malmm", model_type="vicuna7b", is_eval=True, device=device
)`

I encounter this error:

"llm/vicuna-7b is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with huggingface-cli login or by passing token=<your_token>"

How can I resolve this issue?

**Comment by mvsoom** [comment]
You need to manually download Vicuna 7b v1.1 to that folder:
```
[cd to root of this project]
git clone https://huggingface.co/lmsys/vicuna-7b-v1.1 ./llm/vicuna-7b
``` 
This requires git LFS.

Note: LAVIS is also able to fetch lmsys/vicuna-7b-v1.1 directly from HF hub, probably worthwhile to implement that.

**Comment by minjung98** [comment]
Thank you for taking the time. As you instructed, I have manually downloaded the model. However, a new error has occurred now. It seems to be related to the tokenizer. Do you know any solutions? Thank you once again for your prompt response. Below is the error I encountered.
`RuntimeError: Internal: could not parse ModelProto from llm/vicuna-7b/tokenizer.model`

**Comment by boheumd** [comment]
Hi, did you follow the instruction from https://github.com/salesforce/LAVIS/tree/main/projects/instructblip to download the vicuna-7b v1.1 and apply the delta weights to the original LLaMA weights?
Or according to this [issue](https://github.com/salesforce/LAVIS/issues/365#issuecomment-1593017454), you can directly download from this [link](https://huggingface.co/eachadea/vicuna-7b-1.1).

**Comment by minjung98** [comment]
Thank you for your help. However, I still encounter the following error every time I run the command:
`python3 -m fastchat.model.apply_delta \
    --base-model-path /home/minjung/MA-LMM/llm/vicuna-7b\
    --target-model-path /home/minjung/MA-LMM/llm_output/vicuna-7b\
    --delta-path lmsys/vicuna-7b-delta-v1.1`
    The error is:
    `OSError: You seem to have cloned a repository without having git-lfs installed. Please install git-lfs and run 'git lfs install' followed by 'git lfs pull' in the folder you cloned.`
 I have followed the instructions to run git lfs install and git lfs pull, but I keep getting the same error.
 
 I also have another question: Should I clone the repository https://github.com/lm-sys/FastChat.git inside the MA-LMM folder or outside? 
 Thank you once again for your kind response.

**Comment by boheumd** [comment]
I have not came across the same problem before. But you can follow the instruction [here](https://github.com/lm-sys/FastChat/blob/main/docs/vicuna_weights_version.md) to prepare the right vicuna-v1.1 weights. 

You can clone the repository FastChat outside MA-LMM, but only using a soft link to the correct path of vicuna-v1.1.
