### ISSUE TITLE
Run long video rightly

### ISSUE THREAD

**Issue by shuyansy** [boheumd/MA-LMM#8]
Hi, thanks for your great work! Now I am running the demo and want to expand the frames (larger than 20). what parameters should I just？the one in the load_video function or the one in the yaml? Thanks for your time!

**Comment by shuyansy** [comment]
Also, I want to know how to adjust the   "memory_bank_length: 10   num_frames: 20   "  When I expand them, the errors will occur.
![截屏2024-04-30 下午5 27 40](https://github.com/boheumd/MA-LMM/assets/50947689/085d1f0b-ed5d-49f7-843d-c2848ebaa274)

**Comment by boheumd** [comment]
Hello, I have updated the demo.ipynb in the latest version. You can easily specify the memory_bank_length and num_frames when loading the model. Please note that, every time you change the memory_bank_length or num_frames, you need to reload the model again.

**Comment by shuyansy** [comment]
Hi, thanks for the update.However, when I want to load more frames in model , this errors occurs. Do you have any ideas?

![截屏2024-05-01 下午12 38 27](https://github.com/boheumd/MA-LMM/assets/50947689/671c1070-7a4d-4e01-ac09-110c2b0732a0)
![截屏2024-05-01 下午12 38 35](https://github.com/boheumd/MA-LMM/assets/50947689/2590379f-5f01-4068-b620-d1c3eb363cab)

**Comment by boheumd** [comment]
Hello, please check for the latest code update. Currently the max_num_frames is set to 120 by default. If you need to test model on long videos, you need to set the max_num_frames to a larger value in lavis/configs/models/blip2/blip2_instruct_vicuna7b.yaml or lavis/configs/models/blip2/blip2_instruct_vicuna13b.yaml

**Comment by shuyansy** [comment]
It works well now for me. Thanks again for the great work and your effort!
